name: "Find Ongoing Feature Flags"
description: ""
inputs:
  matcher:
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - name: Find Usages
    shell: bash
    run: |
    git grep -E "is_upcoming_features_enabled\('ENG-[0-9]{0,6}'\)" -- '*.py' |
    python ../main.py
