name: "Find Ongoing Feature Flags"
description: ""
inputs:
  matcher:
    required: true
    description: "regex pattern of any code that will be matched"
    type: string
  identifier_matcher:
    required: true
    description: "regex pattern of identifier that is already matched matched"
    type: string
  file_type:
    required: true
    description: "File type that search will happen ex: py"
    type: string
  cutoff_in_days:
    required: true
    description: "date parameter that will notify should be int value as string "
    type: string
runs:
  using: "composite"
  steps:
  - id: search
    shell: bash
    run: echo "::set-output name=result::$var"
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - name: Find Usages
    shell: bash
    run: |
      git grep -E "${{ inputs.matcher }}" -- '*.${{ inputs.file_type }}' |
      python find.py "${{ inputs.identifier_matcher }}" |
      tee >(xargs -I '{}' git log -1 -S '{}' --pretty=format:'(%cd) %n') |
      tac |
      python parse_and_notify.py "${{ inputs.cutoff_in_days }}" | 
      result=$(</dev/stdin)
      echo "$result"
#      Write-Output "::set-output name=result::$result"
