name: "Find Ongoing Feature Flags"
description: ""
inputs:
  matcher:
    required: true
    description: "regex pattern of any code that will be matched"
    type: string
  identifier_matcher:
    required: true
    description: "regex pattern of identifier that is already matched matched"
    type: string
  file_type:
    required: true
    description: "File type that search will happen ex: py"
    type: string
  cutoff_in_days:
    required: true
    description: "date parameter that will notify should be int value as string "
    type: string
outputs:
  results:
    description: "Expired matches"
    value: ${{ steps.search.outputs.results }}
  filtered:
    description: "Filtered matches"
    value: ${{ steps.search.outputs.filtered }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: '0'
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - id: search
    run: |
      pip install -r ${{ github.action_path }}/requirements.txt
      git grep -E "${{ inputs.matcher }}" -- '*.${{ inputs.file_type }}' |
      python ${{ github.action_path }}/find.py "${{ inputs.identifier_matcher }}" |
      tee >(xargs -I '{}' git log -1 -S '{}' --pretty=format:'%aN-(%cd) %n') |
      tac |
      python ${{ github.action_path }}/parse_and_notify.py "${{ inputs.cutoff_in_days }}"
    shell: bash