name: "Find Ongoing Feature Flags"

on:
  workflow_call:
    inputs:
      matcher:
        required: true
        description: "regex pattern of any code that will be matched"
        type: string
      identifier_matcher:
        required: true
        description: "regex pattern of identifier that is already matched matched"
        type: string
      file_type:
        required: true
        description: "File type that search will happen ex: py"
        type: string
      cutoff_in_days:
        required: true
        description: "date parameter that will notify should be int value as string "
        type: string

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/find_ongoing_feature_flags
        with:
          matcher: ${{ inputs.matcher }}
          identifier_matcher: ${{ inputs.identifier_matcher }}
          file_type: ${{ inputs.file_type }}
          cutoff_in_days: ${{ inputs.cutoff_in_days }}