name: "Find Ongoing Feature Flags"

on:
  push:
  workflow_call:
    inputs:
      matcher:
        required: true
        type: string

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/find_ongoing_feature_flags
        with:
          matcher: "is_upcoming_features_enabled\\('ENG-[0-9]{0,6}'\\)"