name: "Find Ongoing Feature Flags"

on:
  push:
  workflow_call:
    inputs:
      matcher:
        required: true
        description: "regex pattern of any code that will be matched"
        type: string
      identifier_matcher:
        required: true
        description: "regex pattern of identifier that is already matched matched"
        type: string
      file_type:
        required: true
        description: "File type that search will happen ex: py"
        type: string
      cutoff_in_days:
        required: true
        description: "date parameter that will notify should be int value as string "
        type: string


jobs:
  cron:
    runs-on: ubuntu-latest
    outputs:
      expired: ${{ steps.search.outputs.expired }}
      filtered: ${{ steps.search.outputs.filtered }}
    steps:
      - uses: actions/checkout@v3
      - id: search
        uses: ByK95/cron-action/.github/actions/find_ongoing_feature_flags@master
        with:
          matcher: "is_upcoming_features_enabled\\('ENG-[0-9]{0,6}'\\)"
          identifier_matcher: "ENG-\\d{0,6}"
          file_type: "py"
          cutoff_in_days: "20"
  job2:
    runs-on: ubuntu-latest
    needs: cron
    steps:
    - run: echo ${{needs.cron.outputs.filtered}}
    - run: echo ${{needs.cron.outputs.expired}}
